<a href="https://colab.research.google.com/github/25wh1a05ce-pixel/NASSCOM/blob/main/WEEK-2/Pandas_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

print("--- Intermediate Pandas Exercise ---")
print("------------------------------------")

s1_1 = pd.Series([10, 20, 30, 40, 50])


np_array1_2 = np.random.randint(1, 101, size=(3, 4))


df1_3 = pd.DataFrame(np_array1_2, columns=['A', 'B', 'C', 'D'])

print("\nSeries:")
print(s1_1)

print("\nNumPy Array:")
print(np_array1_2)

print("\nDataFrame:")
print(df1_3)


--- Intermediate Pandas Exercise ---
------------------------------------

Series:
0    10
1    20
2    30
3    40
4    50
dtype: int64

NumPy Array:
[[78 23 64 63]
 [12 28 95 25]
 [33 65 33 71]]

DataFrame:
    A   B   C   D
0  78  23  64  63
1  12  28  95  25
2  33  65  33  71


In [5]:
dates = pd.date_range(start='2023-01-01', periods=100)

df_sales = pd.DataFrame({
    'Date': dates,
    'Region': np.random.choice(['East', 'West', 'North', 'South'], 100),
    'Product': np.random.choice(['Laptop', 'Mouse', 'Keyboard', 'Monitor'], 100),
    'Sales': np.random.randint(100, 1001, 100).astype(float),
    'Quantity': np.random.randint(1, 11, 100).astype(float)
})
sales_nan_idx = np.random.choice(df_sales.index, 5, replace=False)
df_sales.loc[sales_nan_idx, 'Sales'] = np.nan


qty_nan_idx = np.random.choice(df_sales.index, 3, replace=False)
df_sales.loc[qty_nan_idx, 'Quantity'] = np.nan

print("\nFirst 5 Rows:")
print(df_sales.head())




First 5 Rows:
        Date Region   Product  Sales  Quantity
0 2023-01-01   East    Laptop  848.0      10.0
1 2023-01-02   West   Monitor  681.0       4.0
2 2023-01-03  North  Keyboard  834.0       3.0
3 2023-01-04  South  Keyboard  605.0       8.0
4 2023-01-05   East     Mouse  438.0       4.0


In [6]:
df3_1 = df_sales[['Region', 'Sales']]


df3_2 = df_sales[df_sales['Product'] == 'Laptop']


df3_3 = df_sales[
    (df_sales['Region'] == 'East') &
    (df_sales['Sales'] > 500)
]


monitor_index = df_sales[df_sales['Product'] == 'Monitor'].index[0]

val3_4 = df_sales.loc[monitor_index, 'Sales']

print("\nRegion and Sales:")
print(df3_1.head())

print("\nLaptop Records:")
print(df3_2.head())

print("\nEast Region with Sales > 500:")
print(df3_3.head())

print("\nFirst Monitor Sales:", val3_4)




Region and Sales:
  Region  Sales
0   East  848.0
1   West  681.0
2  North  834.0
3  South  605.0
4   East  438.0

Laptop Records:
         Date Region Product  Sales  Quantity
0  2023-01-01   East  Laptop  848.0      10.0
5  2023-01-06   West  Laptop  389.0       6.0
13 2023-01-14   East  Laptop  806.0       6.0
15 2023-01-16  North  Laptop  762.0       8.0
16 2023-01-17   East  Laptop  694.0       1.0

East Region with Sales > 500:
         Date Region  Product  Sales  Quantity
0  2023-01-01   East   Laptop  848.0      10.0
7  2023-01-08   East  Monitor  846.0       NaN
10 2023-01-11   East    Mouse  571.0       3.0
13 2023-01-14   East   Laptop  806.0       6.0
16 2023-01-17   East   Laptop  694.0       1.0

First Monitor Sales: 681.0


In [7]:
missing_counts4_1 = df_sales.isnull().sum()


df4_2_filled = df_sales.copy()

sales_mean = df4_2_filled['Sales'].mean()

df4_2_filled['Sales'].fillna(sales_mean, inplace=True)


df4_3_dropped = df_sales.dropna()

print("\nMissing Values:")
print(missing_counts4_1)

print("\nFilled Data:")
print(df4_2_filled.head())

print("\nDropped Missing Values:")
print(df4_3_dropped.head())




Missing Values:
Date        0
Region      0
Product     0
Sales       5
Quantity    3
dtype: int64

Filled Data:
        Date Region   Product  Sales  Quantity
0 2023-01-01   East    Laptop  848.0      10.0
1 2023-01-02   West   Monitor  681.0       4.0
2 2023-01-03  North  Keyboard  834.0       3.0
3 2023-01-04  South  Keyboard  605.0       8.0
4 2023-01-05   East     Mouse  438.0       4.0

Dropped Missing Values:
        Date Region   Product  Sales  Quantity
0 2023-01-01   East    Laptop  848.0      10.0
1 2023-01-02   West   Monitor  681.0       4.0
2 2023-01-03  North  Keyboard  834.0       3.0
3 2023-01-04  South  Keyboard  605.0       8.0
4 2023-01-05   East     Mouse  438.0       4.0


/tmp/ipykernel_854/754433008.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df4_2_filled['Sales'].fillna(sales_mean, inplace=True)


In [8]:
df_sales['Total_Revenue'] = df_sales['Sales'] * df_sales['Quantity']


df5_2_sorted = df_sales.sort_values(
    by=['Date', 'Sales'],
    ascending=[True, False]
)


df5_3_grouped_region = df_sales.groupby('Region')[['Sales', 'Quantity']].sum()


df5_4_grouped_product = df_sales.groupby('Product')['Sales'].mean()

print("\nData with Total Revenue:")
print(df_sales.head())

print("\nSorted Data:")
print(df5_2_sorted.head())

print("\nGrouped by Region:")
print(df5_3_grouped_region)

print("\nAverage Sales by Product:")
print(df5_4_grouped_product)


Data with Total Revenue:
        Date Region   Product  Sales  Quantity  Total_Revenue
0 2023-01-01   East    Laptop  848.0      10.0         8480.0
1 2023-01-02   West   Monitor  681.0       4.0         2724.0
2 2023-01-03  North  Keyboard  834.0       3.0         2502.0
3 2023-01-04  South  Keyboard  605.0       8.0         4840.0
4 2023-01-05   East     Mouse  438.0       4.0         1752.0

Sorted Data:
        Date Region   Product  Sales  Quantity  Total_Revenue
0 2023-01-01   East    Laptop  848.0      10.0         8480.0
1 2023-01-02   West   Monitor  681.0       4.0         2724.0
2 2023-01-03  North  Keyboard  834.0       3.0         2502.0
3 2023-01-04  South  Keyboard  605.0       8.0         4840.0
4 2023-01-05   East     Mouse  438.0       4.0         1752.0

Grouped by Region:
          Sales  Quantity
Region                   
East    15252.0     147.0
North   12031.0     104.0
South   10218.0     128.0
West    18426.0     156.0

Average Sales by Product:
Product
Keybo